apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellocloud-container
spec:
  selector:
    matchLabels:
      app: hellocloud-container
  replicas: 1
  template:
    metadata:
      labels:
        app: hellocloud-container
    spec:
      containers:
        - name: hellocloud-container
          image: ieielil/python-container:v5
          resources:
            limits:
              memory: 50M
        - name: shell
          image: centos:7
          command:
            - sh
            - '-c'
            - sleep 1000