apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-pset-1
spec:
  selector:
    matchLabels:
      app: hc-pset-1
  replicas: 1
  template:
    metadata:
      labels:
        app: hc-pset-1
    spec:
      containers:
        - name: shell
          image: centos:7
          command:
            - sh
            - '-c'
            - echo "HELLOCLOUD ~ I AM HERE"
